<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ui_patterns\UiPatterns;

/**
 * Implements hook_page_attachments.
 */
function jumpstart_ui_page_attachments(array &$page) {

  // Uncomment to add a library to all pages. It is recommended that you don't
  // just add a library to all pages but rather, conditionally require this
  // library only where it is needed.
  // See: https://www.drupal.org/node/2274843

  // Only add on non-admin pages.
  if (\Drupal::service('router.admin_context')->isAdminRoute() == FALSE) {
    $page['#attached']['library'][] = 'jumpstart_ui/base';
    $page['#attached']['library'][] = 'jumpstart_ui/layout';
    $page['#attached']['library'][] = 'jumpstart_ui/jumpstart_ui';
  }

}

/**
 * Implements hook_preprocess().
 */
function jumpstart_ui_preprocess(&$variables, $hook) {
  $moduleHandler = \Drupal::service('module_handler');
  if (!$moduleHandler->moduleExists('ui_patterns')) {
    return;
  }

  foreach (UiPatterns::getPatternDefinitions() as $pattern_id => $pattern) {
    if (strpos($hook, $pattern_id) !== FALSE) {
      $ids = &drupal_static(__FUNCTION__, []);
      if (!isset($ids[$pattern_id])) {
        $ids[$pattern_id] = 0;
      }

      if (!isset($variables['attributes']['id'])) {
        $variables['attributes']['id'] = Html::getUniqueId($pattern_id);
      }

      $definition = $pattern->toArray();
      if (isset($variables['variant']) && isset($definition['variants'][$variables['variant']]['modifier_class'])) {
        $variables['modifier_class'] = $definition['variants'][$variables['variant']]['modifier_class'];
      }

      break;
    }
  }
}

/**
 * Implements hook_preprocess_patterns_overview_page().
 */
function jumpstart_ui_preprocess_patterns_overview_page(&$variables) {
  uasort($variables['patterns'], function ($pattern_a, $pattern_b) {
    return strcmp($pattern_a['label'], $pattern_b['label']);
  });
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add validation to field add form.
 */
function jumpstart_ui_form_field_ui_field_storage_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'jumpstart_ui_field_storage_add_validate';
}

/**
 * Field storage add validation to prevent hashed table names.
 *
 * @see \Drupal\Core\Entity\Sql\DefaultTableMapping::generateFieldTableName()
 */
function jumpstart_ui_field_storage_add_validate(&$form, FormStateInterface $form_state) {
  $entity_type = $form_state->getBuildInfo()['args'][0];
  $field_name = $form_state->getValue('field_name');
  $field_prefix = \Drupal::config('field_ui.settings')->get('field_prefix');

  // When a table name is over 48 characters, Drupal will hash the field name
  // to create a shorter field table. This makes it nearly impossible to track
  // down exactly what table is for what field without inspecting the field
  // storage config entity.
  if (strlen("{$entity_type}_revision__{$field_prefix}$field_name") > 48) {
    $form_state->setError($form['new_storage_wrapper']['field_name'], t('Field name is too long. Please keep this field name under @count characters'));
  }
}
