<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\ui_patterns\UiPatterns;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_page_attachments.
 */
function jumpstart_ui_page_attachments(array &$page) {

  // It is recommended that you don't just add a library to all pages but
  // rather, conditionally require this library only where it is needed.
  // See: https://www.drupal.org/node/2274843

  // Only add on non-admin pages.
  if (\Drupal::service('router.admin_context')->isAdminRoute() == FALSE) {
    $page['#attached']['library'][] = 'jumpstart_ui/base';
    $page['#attached']['library'][] = 'jumpstart_ui/layout';
    $page['#attached']['library'][] = 'jumpstart_ui/jumpstart_ui';
  }

}

/**
 * Implements hook_preprocess().
 */
function jumpstart_ui_preprocess(&$variables, $hook) {
  $moduleHandler = \Drupal::service('module_handler');
  if (!$moduleHandler->moduleExists('ui_patterns')) {
    return;
  }

  foreach (UiPatterns::getPatternDefinitions() as $pattern_id => $pattern) {
    if (strpos($hook, $pattern_id) !== FALSE) {
      $ids = &drupal_static(__FUNCTION__, []);
      if (!isset($ids[$pattern_id])) {
        $ids[$pattern_id] = 0;
      }

      if (!isset($variables['attributes']['id'])) {
        $variables['attributes']['id'] = Html::getUniqueId($pattern_id);
      }

      $definition = $pattern->toArray();
      if (isset($variables['variant']) && isset($definition['variants'][$variables['variant']]['modifier_class'])) {
        $variables['modifier_class'] = $definition['variants'][$variables['variant']]['modifier_class'];
      }

      break;
    }
  }
}

/**
 * Implements hook_preprocess_patterns_overview_page().
 */
function jumpstart_ui_preprocess_patterns_overview_page(&$variables) {
  uasort($variables['patterns'], function ($pattern_a, $pattern_b) {
    return strcmp($pattern_a['label'], $pattern_b['label']);
  });
}
